### ISSUE TITLE
Classes removed in a2c653a

### ISSUE THREAD

**Issue by egkoppel** [zno-project/znoc#3]
Support for parsing `class` (previously just an alias to `struct`) was removed in a2c653a
Potential fixes:
- Add back `class` keyword as alias to `struct`
- Add support for member functions in structs and remove concept of classes
- Add extensions (see #1) and allow struct member functions in extensions

@hiornso thoughts?

**Comment by hiornso** [comment]
I favour option 2

**Comment by Liftyee** [comment]
looks fine to me
